### PR TITLE
Refactor V2 support

### PR DESCRIPTION
**Pull request by drinfernoo**
This is working for me, and hopefully simplifies the code a bit, making it easier to handle potentially different sensors in the future.

### CODE REVIEW

**Comment by drinfernoo** [comment]
I'm also thinking it may not be worth checking against a leak sensor? As far as I can tell, Wyze has never made one 🤔

**Comment by AK5nowman** [comment]
Looks good to me. I’ll merge in tonight. 

For the leak sensors. There is another series of sensors that use the same hardware, which also made a leak sensor. See https://github.com/HclX/WyzeSensePy/pull/13

**Comment by drinfernoo** [comment]
I'm going to take a look at another potential improvement: It would be nice if this would put the correct `device_class` in `sensors.yaml` from the get-go... instead of having to edit it after the fact.

**Comment by drinfernoo** [comment]
Ok, so I think I've got it covered now. We automatically add the proper `class` to the `sensors.yaml` depending on what device is added. This obviously doesn't have any way to add `window` or `door`... but the basics are covered.

The only thing I'm not super happy with here is: https://github.com/drinfernoo/wyzesense2mqtt/blob/dev_v2Basic/wyzesense2mqtt/wyzesense2mqtt.py#L446

`device = [DEVICE_CLASSES[i] for i in DEVICE_CLASSES if DEVICE_CLASSES[i].get('type') == sensor_type][0]`

It's a little bit "hacky", but shouldn't ever have any issue unless there are multiple physical devices with the same device "type" but a different "ID" and "class". For example, if for some reason there was a device in the future that acted like a contact sensor, but reported as if it was a motion sensor with an ID of `0x0D` or something... I don't really see that happening 😉

**Comment by drinfernoo** [comment]
Ah, I found a much better way of handling the `device_class`es now 😁

This one should be pretty easy to add possible future devices too, and shouldn't break either :+1:

I've also allowed them to potentially return `None`, as it shouldn't break *our* code, and HA should handle `None` by creating a "generic" on/off `binary_sensor`.

**Comment by drinfernoo** [comment]
The last few commits weren't tested directly, but I expect them to be safe, as they're simple refactors for clarity and consistency.

**Comment by AK5nowman** [comment]
When I developed my C# library I started going down the path of defining each sensor type in the core (wyzesense.py) but eventually realized I didn't want to have to edit the core code each time a basic sensor type is added. Started to refactor things so the device type and state was assigned at the "application" layer (wyzesense2mqtt.py)

All these edits look good to me though. Making it more robust, that is for sure.

**Pull request merged**
